package mlkemkem

import (
	"bytes"
	cryptorand "crypto/rand"
	"encoding/binary"
	"fmt"
	"math/rand"
	"strings"

	// Use circl because gocrypto does not support 512.
	// This is OK because it's for testing.

	"github.com/cloudflare/circl/kem"
	"github.com/cloudflare/circl/kem/mlkem/mlkem1024"
	"github.com/cloudflare/circl/kem/mlkem/mlkem512"
	"github.com/cloudflare/circl/kem/mlkem/mlkem768"

	"github.com/chrisfenner/tpm-test-vectors/pkg/util"
	"github.com/google/go-tpm/tpm2"
	"github.com/google/go-tpm/tpm2/transport"
)

type TestVector struct {
	Name        string
	Description string
	Label       string
	Randomness  util.HexBytes
	PublicKey   util.HexBytes
	PrivateKey  util.HexBytes
	Secret      util.HexBytes
	Ciphertext  util.HexBytes
}

func (v *TestVector) VectorName() string {
	return v.Name
}

func (v *TestVector) SetName(name string) {
	v.Name = name
}

// Mock out TPMI_MLKEM_PARMS, since go-tpm doesn't support it yet.
type tpmiMLKEMParms uint16

const (
	tpmMLKEM512  tpmiMLKEMParms = 0x0001
	tpmMLKEM768  tpmiMLKEMParms = 0x0002
	tpmMLKEM1024 tpmiMLKEMParms = 0x0003
)

func (p tpmiMLKEMParms) String() string {
	switch p {
	case tpmMLKEM512:
		return "512"
	case tpmMLKEM768:
		return "768"
	case tpmMLKEM1024:
		return "1024"
	}
	return fmt.Sprintf("unrecognized parameter set ID 0x%x", uint16(p))
}

func randomParameterSet() (func(seed []byte) (kem.PublicKey, kem.PrivateKey), tpmiMLKEMParms) {
	switch rand.Intn(3) {
	case 0:
		return func(seed []byte) (kem.PublicKey, kem.PrivateKey) {
			pub, priv := mlkem512.NewKeyFromSeed(seed)
			return pub, priv
		}, tpmMLKEM512
	case 1:
		return func(seed []byte) (kem.PublicKey, kem.PrivateKey) {
			pub, priv := mlkem768.NewKeyFromSeed(seed)
			return pub, priv
		}, tpmMLKEM768
	}
	return func(seed []byte) (kem.PublicKey, kem.PrivateKey) {
		pub, priv := mlkem1024.NewKeyFromSeed(seed)
		return pub, priv
	}, tpmMLKEM1024
}

// Marshal a fake ML-KEM public area to a TPMT_PUBLIC by hand
func tpmifyPublicKey(pub kem.PublicKey, nameAlg tpm2.TPMIAlgHash, parms tpmiMLKEMParms) []byte {
	// Get the encoded public key bytes
	pubBytes, err := pub.MarshalBinary()
	if err != nil {
		panic(fmt.Sprintf("unexpected error from pub.MarshalBinary(): %v", err))
	}

	var tpmtpub bytes.Buffer
	// TPM_ALG_MLKEM
	binary.Write(&tpmtpub, binary.BigEndian, tpm2.TPMAlgID(0x00A0))
	binary.Write(&tpmtpub, binary.BigEndian, nameAlg)
	// We don't need as much diversity in the attributes for ML-KEM as for ECC and RSA, because the
	// scheme does not depend on anything but the name alg and the parameter set.
	// For basic realism, just fake out an unrestriced ML-KEM key generated by the TPM.
	tpmtpub.Write(tpm2.Marshal(tpm2.TPMAObject{
		FixedTPM:             false,
		STClear:              false,
		FixedParent:          false,
		SensitiveDataOrigin:  true,
		UserWithAuth:         true,
		AdminWithPolicy:      false,
		FirmwareLimited:      false,
		NoDA:                 true,
		EncryptedDuplication: false,
		Restricted:           false,
		Decrypt:              true,
		SignEncrypt:          false,
		X509Sign:             false,
	}))
	// Empty policy
	tpmtpub.Write(tpm2.Marshal(tpm2.TPM2BDigest{}))
	// parameters.symmetric
	binary.Write(&tpmtpub, binary.BigEndian, tpm2.TPMAlgNull)
	// parameters.parameterSet
	binary.Write(&tpmtpub, binary.BigEndian, parms)
	// unique
	tpmtpub.Write(tpm2.Marshal(tpm2.TPM2BData{
		Buffer: pubBytes,
	}))
	return tpmtpub.Bytes()
}

// Marshal a fake ML-KEM private seed to a TPMT_SENSITIVE by hand
func tpmifyPrivateKey(seed []byte, nameAlg tpm2.TPMIAlgHash) []byte {
	nameAlgHash, err := nameAlg.Hash()
	if err != nil {
		panic(fmt.Sprintf("nameAlg.Hash() = %v", err))
	}
	var tpmtsensitive bytes.Buffer
	// TPM_ALG_MLKEM
	binary.Write(&tpmtsensitive, binary.BigEndian, tpm2.TPMAlgID(0x00A0))
	// Empty auth value
	tpmtsensitive.Write(tpm2.Marshal(tpm2.TPM2BAuth{
		Buffer: make([]byte, nameAlgHash.Size()),
	}))
	// Empty protection seed value
	tpmtsensitive.Write(tpm2.Marshal(tpm2.TPM2BDigest{
		Buffer: make([]byte, nameAlgHash.Size()),
	}))
	// ML-KEM private seed value
	tpmtsensitive.Write(tpm2.Marshal(tpm2.TPM2BData{
		Buffer: seed,
	}))
	return tpmtsensitive.Bytes()
}

// GenerateTestVector generates an ML-KEM Labeled Encapsulation test vector.
// It does not use the TPM because the TPM simulator+Go-TPM does not yet support ML-KEM Labeled KEM.
func GenerateTestVector(_ transport.TPM) (*TestVector, error) {
	var testName strings.Builder
	var testDescription strings.Builder

	newFromSeed, parmName := randomParameterSet()
	fmt.Fprintf(&testName, "MLKEM%s", parmName)
	fmt.Fprintf(&testDescription, "ML-KEM-%s", parmName)

	nameAlg := util.RandomHashAlg()
	nameAlgHash, _ := nameAlg.Hash()
	fmt.Fprintf(&testName, "_%s", util.PrettyAlgName(nameAlg))
	fmt.Fprintf(&testDescription, " using name alg %s", util.PrettyAlgName(nameAlg))

	var seed [64]byte
	cryptorand.Read(seed[:])
	pub, _ := newFromSeed(seed[:])
	pubBytes, _ := pub.MarshalBinary()
	var randomness [32]byte
	cryptorand.Read(randomness[:])
	ct, ss, err := pub.Scheme().EncapsulateDeterministically(pub, randomness[:])
	if err != nil {
		return nil, err
	}
	label := util.RandomEncapsulationLabel()
	sharedSecret := tpm2.KDFa(nameAlgHash, ss, label, ct, pubBytes, nameAlgHash.Size()*8)

	return &TestVector{
		Name:        testName.String(),
		Description: testDescription.String(),
		Label:       label,
		Randomness:  randomness[:],
		PublicKey:   tpmifyPublicKey(pub, nameAlg, parmName),
		PrivateKey:  tpmifyPrivateKey(seed[:], nameAlg),
		Secret:      sharedSecret,
		Ciphertext:  ct,
	}, nil
}
